# Generated by Django 5.1 on 2024-10-16 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
    ]
